name: Test and Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run tests with coverage
      run: yarn test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true